name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          BASE_PATH: '/evidence_sample'
        run: |
          npm run sources
          npm run build

      - name: Check Build Directory
        run: ls -R build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages # ここを追加

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
